const at = (day, time) => `2026-10-${day}T${time}:00+05:30`;
const booking = (
  id,
  type,
  title,
  provider,
  day,
  start,
  end,
  from,
  to,
  price,
  refund,
  dependencies = [],
) => ({
  id,
  type,
  title,
  provider,
  start: at(day, start),
  end: at(day, end),
  from,
  to,
  price,
  refund,
  dependencies,
  status: "confirmed",
  reference: `WP-${id.toUpperCase()}26`,
  refundDeadline: at("11", "23:59"),
});
export function seed() {
  const bookings = [
    booking(
      "flight",
      "flight",
      "Delhi → Jaipur",
      "IndiGo · 6E 204",
      "12",
      "08:00",
      "09:00",
      "DEL",
      "JAI",
      4200,
      0.75,
    ),
    booking(
      "transfer",
      "transfer",
      "Airport → your hotel",
      "Pink City Transfers",
      "12",
      "09:45",
      "10:30",
      "JAI",
      "Jaipur",
      850,
      0.5,
      [{ id: "flight", buffer: 45 }],
    ),
    booking(
      "hotel",
      "hotel",
      "Check in at the Alsisar Haveli",
      "Heritage stay · 2 nights",
      "12",
      "11:00",
      "11:30",
      "Jaipur",
      "Jaipur",
      9600,
      0.5,
      [{ id: "transfer", buffer: 20 }],
    ),
    booking(
      "tour",
      "activity",
      "The old city, a little closer",
      "Hawa Mahal & City Palace walking tour",
      "12",
      "12:30",
      "15:00",
      "Jaipur",
      "Jaipur",
      1800,
      0,
      [{ id: "hotel", buffer: 30 }],
    ),
    booking(
      "dinner",
      "event",
      "An evening above the Pink City",
      "Rooftop dinner · Bar Palladio",
      "12",
      "19:00",
      "20:30",
      "Jaipur",
      "Jaipur",
      2400,
      0.5,
      [{ id: "tour", buffer: 45 }],
    ),
    booking(
      "fort",
      "activity",
      "A morning at Amber Fort",
      "Guided architecture & history tour",
      "13",
      "09:00",
      "12:00",
      "Jaipur",
      "Jaipur",
      1600,
      1,
      [],
    ),
    booking(
      "train",
      "train",
      "Jaipur → Delhi",
      "Ajmer Shatabdi · 12016",
      "14",
      "17:45",
      "22:40",
      "Jaipur",
      "DEL",
      1450,
      0.75,
      [],
    ),
  ];
  const offers = [];
  for (const b of bookings) {
    for (const [i, shift, multiplier] of [
      [1, 120, 1.15],
      [2, 240, 0.95],
      [3, 360, 0.8],
    ]) {
      offers.push({
        ...b,
        id: `${b.id}-alt-${i}`,
        bookingId: b.id,
        title: b.title,
        provider:
          b.type === "flight"
            ? ["Air India · AI 612", "IndiGo · 6E 218", "Air India · AI 614"][
                i - 1
              ]
            : `${b.provider.split(" · ")[0]} · later slot`,
        start: new Date(Date.parse(b.start) + shift * 60000).toISOString(),
        end: new Date(Date.parse(b.end) + shift * 60000).toISOString(),
        price: Math.round(b.price * multiplier),
        seats: 4,
        accessible: i !== 3,
      });
    }
  }
  return {
    version: 1,
    trip: {
      id: "pink-city",
      name: "A little escape to Jaipur",
      subtitle: "Palaces, pink streets & a slower pace.",
      destination: "Jaipur, India",
      travelers: 2,
      start: "2026-10-12",
      end: "2026-10-14",
      bookings,
    },
    offers,
    preferences: { budget: 15000, priority: "balanced", accessible: false },
    disruptions: [],
    history: [],
  };
}
