import React, { useState } from "react";
import { Plane, MapPin, CalendarDays, Clock, Users, Moon, IndianRupee, Coins, Scale, Crown, Camera, Mountain, Utensils, Leaf, ShoppingBag, Music, Palmtree, Landmark, Flower2, PawPrint, Check, Search, ArrowRight, ArrowLeftRight, Zap, ShieldCheck, Star, Bell, ChevronRight, ChevronDown, Lightbulb } from "lucide-react";
import { destinations, TripPhoto } from "./BuilderVisuals";
import "./manual-trip.css";

const cities = {
  Mumbai: ["BOM", "Chhatrapati Shivaji Maharaj Intl."], Jaipur: ["JAI", "Jaipur International Airport"], Delhi: ["DEL", "Indira Gandhi International Airport"], Goa: ["GOI", "Goa International Airport"], Udaipur: ["UDR", "Maharana Pratap Airport"], Bengaluru: ["BLR", "Kempegowda International Airport"], Agra: ["AGR", "Agra Airport"], Varanasi: ["VNS", "Lal Bahadur Shastri Airport"],
};
const photos = [...destinations.filter((d) => ["Jaipur", "Delhi", "Goa", "Udaipur"].includes(d.name)).map((d) => d.name === "Udaipur" ? { ...d, image: "/images/build-welcome/udaipur-lake.jpg" } : d), { name: "Bengaluru", image: "/images/build-welcome/bangalore.jpg" }, { name: "Varanasi", image: "/images/build-welcome/varanasi-ghats.jpg" }];
const interestOptions = [[Camera,"Sightseeing"],[Mountain,"Adventure"],[Utensils,"Food"],[Leaf,"Nature"],[ShoppingBag,"Shopping"],[Music,"Nightlife"],[Palmtree,"Beaches"],[Landmark,"Culture"],[Flower2,"Relaxation"],[PawPrint,"Wildlife"]];
const nextWeek = () => new Date(Date.now() + 7 * 86400000).toISOString().slice(0,10);
export function ManualTrip({ onStart, busy, error, user }) {
  const requested = new URLSearchParams(window.location.search).get("destination");
  const [form, setForm] = useState({ origin: requested === "Mumbai" ? "Delhi" : "Mumbai", destination: cities[requested] ? requested : "Jaipur", date: nextWeek(), time: "", travelers: 1, durationDays: 3, budget: 20000 });
  const [roundTrip, setRoundTrip] = useState(false);
  const [returnDate, setReturnDate] = useState("");
  const [style, setStyle] = useState("Budget");
  const [interests, setInterests] = useState(["Sightseeing"]);
  const [all, setAll] = useState(false);
  const [search, setSearch] = useState("");
  const set = (key) => (event) => setForm({ ...form, [key]: event.target.value });
  const place = photos.find((p) => p.name === form.destination) || destinations.find((p) => p.name === form.destination);
  const shown = (all ? [...photos, ...destinations.filter((p) => !photos.some((d) => d.name === p.name))] : photos).filter((p) => p.name.toLowerCase().includes(search.toLowerCase()));
  return <div className="manual-trip">
    <header className="manual-topbar"><a className="manual-brand" href="/build"><Plane size={35} fill="currentColor" /><span><b>TravelCompanion</b><small>Plan · Recover · Explore</small></span></a><label className="manual-search"><Search size={17} /><input aria-label="Search destinations" placeholder="Search destinations, hotels, activities…" value={search} onChange={(e) => setSearch(e.target.value)} /></label><div className="manual-account"><a className="manual-notification" href="/notifications" aria-label="Notifications"><Bell size={20} /><i /></a><a className="manual-avatar" href="/account" aria-label="Account">{user?.name?.[0] || "T"}</a><a className="manual-account-name" href="/account">{user?.name?.split(" ")[0] || "Traveler"}</a><a className="manual-account-chevron" href="/account" aria-label="Account menu"><ChevronDown size={15} /></a></div></header>
    <div className="manual-workspace"><div className="manual-main"><div className="manual-content"><div className="manual-breadcrumb"><a href="/dashboard">Home</a><ChevronRight size={12} /><a href="/build?mode=manual">Trip Planner</a><ChevronRight size={12} /><span>Build My Trip</span></div>
      <div className="manual-heading"><div><Plane size={36} fill="currentColor" /><section><h1>Build My Trip</h1><p>Enter your trip details and we’ll find the best options for flights, hotels, transport, activities and more.</p></section></div><ol className="manual-steps" aria-label="Trip progress">{["Trip Details","Search","Review & Edit","Confirm"].map((label,i)=><li key={label} className={i===0?"active":""}><b>{i+1}</b><span>{label}</span>{i<3&&<ArrowRight size={14}/>}</li>)}</ol></div>
      <div className="manual-columns"><form className="manual-form" onSubmit={(e)=>{e.preventDefault(); onStart({...form, mode:"manual", travelers:Number(form.travelers), durationDays:Number(form.durationDays), budget:Number(form.budget), time:form.time || "09:00", ...(roundTrip?{returnDate}:{}), preferences:{hotelStars:style==="Premium"?5:style==="Balanced"?4:3,activities:interests}});}}>
        <div className="manual-trip-types">{[false,true].map((value)=><button type="button" aria-pressed={roundTrip===value} key={String(value)} className={roundTrip===value?"selected":""} onClick={()=>setRoundTrip(value)}><span>{roundTrip===value&&<Check size={12}/>}</span>{value?"Round Trip":"One Way"}</button>)}<button type="button" disabled title="Multi-city planning is not available in this demo"><span/>Multi City</button></div>
        <div className="manual-route"><label><Plane size={23}/><div><span>From</span><select aria-label="From" value={form.origin} onChange={set("origin")}>{Object.entries(cities).map(([name,[code]])=><option key={name} value={name}>{name} ({code})</option>)}</select><small>{cities[form.origin][1]}</small></div></label><button type="button" className="manual-swap" aria-label="Swap origin and destination" onClick={()=>setForm({...form,origin:form.destination,destination:form.origin})}><ArrowLeftRight size={18}/></button><label><MapPin size={24}/><div><span>To</span><select aria-label="To" value={form.destination} onChange={set("destination")}>{Object.entries(cities).map(([name,[code]])=><option key={name} value={name} disabled={name===form.origin}>{name} ({code})</option>)}</select><small>{cities[form.destination][1]}</small></div></label></div>
        <div className="manual-fields"><label><CalendarDays/><div><span>Departure Date</span><input type="date" aria-label="Departure date" required value={form.date} onChange={set("date")}/></div></label><label><Clock/><div><span>Departure Time</span><select aria-label="Departure time" value={form.time} onChange={set("time")}><option value="">Any time</option>{["06:00","09:00","12:00","15:00","18:00","21:00"].map(t=><option key={t}>{t}</option>)}</select></div></label><label><Users/><div><span>Travelers</span><select aria-label="Travelers" value={form.travelers} onChange={set("travelers")}>{Array.from({length:10},(_,i)=><option key={i+1} value={i+1}>{i+1} Traveler{i?"s":""}</option>)}</select></div></label><label><Moon/><div><span>Trip Duration</span><select aria-label="Trip duration" value={form.durationDays} onChange={set("durationDays")}>{Array.from({length:14},(_,i)=><option key={i+1} value={i+1}>{i} Night{i!==1?"s":""} ({i+1} Day{i?"s":""})</option>)}</select></div></label>{roundTrip&&<label><CalendarDays/><div><span>Return Date</span><input type="date" aria-label="Return date" required min={form.date} value={returnDate} onChange={(e)=>setReturnDate(e.target.value)}/></div></label>}<label className="manual-budget"><IndianRupee/><div><span>Budget (Optional)</span><input type="number" aria-label="Budget in INR" min={0} step={500} value={form.budget} onChange={set("budget")}/></div></label></div>
        <section className="manual-preference"><h2>Travel Style</h2><div className="manual-styles">{[[Coins,"Budget","Best value options within your budget"],[Scale,"Balanced","Good mix of cost and comfort"],[Crown,"Premium","More comfort and premium options"]].map(([Icon,name,text])=><button type="button" aria-label={`${name} ${text}`} aria-pressed={style===name} key={name} className={style===name?"selected":""} onClick={()=>setStyle(name)}><span><Icon size={27}/></span><div><b>{name}</b><small>{text}</small></div></button>)}</div></section>
        <section className="manual-preference"><h2>Interests <span>(Optional)</span></h2><div className="manual-interests">{interestOptions.map(([Icon,label],i)=><button type="button" key={label} aria-pressed={interests.includes(label)} className={`interest-color-${i} ${interests.includes(label)?"selected":""}`} onClick={()=>setInterests(interests.includes(label)?interests.filter(x=>x!==label):[...interests,label])}><Icon size={19}/>{label}</button>)}</div></section>
        <section className="manual-preference"><div className="manual-destination-heading"><h2>Popular Destinations</h2><button type="button" onClick={()=>setAll(!all)}>{all?"Show Less":"View All"} <ArrowRight size={14}/></button></div><div className="manual-destinations">{shown.map(p=><button type="button" aria-pressed={form.destination===p.name} key={p.name} className={form.destination===p.name?"selected":""} onClick={()=>setForm({...form,destination:p.name,origin:form.origin===p.name?(p.name==="Mumbai"?"Delhi":"Mumbai"):form.origin})}><TripPhoto src={p.image} alt={p.name}/><b>{p.name==="Bengaluru"?"Bangalore":p.name}</b></button>)}</div>{!shown.length&&<p className="manual-note">No destinations match your search.</p>}</section>
        {error&&<p className="error" role="alert">{error}</p>}{form.origin===form.destination&&<p className="error" role="alert">Choose different departure and destination cities.</p>}
        <button className="manual-submit" disabled={busy||form.origin===form.destination}><Search size={21}/>{busy?"Searching for your trip…":"Search & Build My Trip"}<ArrowRight size={21}/></button><p className="manual-note">We’ll search flights, hotels, transport, restaurants and activities for the best options.</p>
      </form>
      <aside className="manual-aside"><div className="manual-city-photo"><TripPhoto src={place?.image || destinations[0].image} alt={form.destination}/><div><h2><MapPin size={24} fill="currentColor"/>{form.destination}</h2><p>{form.destination==="Jaipur"?"Royal palaces, rich culture and vibrant markets await you in the Pink City.":"Discover local favourites, beautiful places and a journey to make your own."}</p></div></div><section className="manual-benefits"><h2>Why Plan with Us?</h2>{[[Zap,"More options","Compare flights, hotels, transport and more in one place."],[ShieldCheck,"Smart itinerary","Get a complete day-by-day plan with timings and cost."],[IndianRupee,"Budget control","Stay within your budget with the best options."],[Star,"Explore more","Discover activities, restaurants and hidden gems."]].map(([Icon,title,text],i)=><div key={title} className={`benefit-${i}`}><span><Icon size={25}/></span><section><b>{title}</b><p>{text}</p></section></div>)}</section><section className="manual-tip"><Lightbulb size={24}/><div><h2>Tip</h2><p>You can also use AI Recovery if your plans have changed or you need a new plan due to a disruption.</p><a href="/build?mode=auto">Try AI Recovery <ArrowRight size={16}/></a></div></section></aside></div>
      </div></div></div>
  </div>;
}
